CREATE TABLE `trainer_media` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trainerId` int NOT NULL,
	`type` enum('profile_photo','gallery_image','video') NOT NULL,
	`url` text NOT NULL,
	`thumbnailUrl` text,
	`title` varchar(255),
	`description` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`videoProvider` enum('youtube','vimeo','upload'),
	`videoId` varchar(64),
	`fileKey` varchar(512),
	`mimeType` varchar(100),
	`fileSize` int,
	`width` int,
	`height` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trainer_media_id` PRIMARY KEY(`id`)
);
