CREATE TABLE `bundle_invitations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trainerId` int NOT NULL,
	`bundleId` int NOT NULL,
	`email` varchar(320) NOT NULL,
	`recipientName` varchar(255),
	`token` varchar(64) NOT NULL,
	`personalMessage` text,
	`status` enum('pending','viewed','accepted','declined','expired') DEFAULT 'pending',
	`acceptedByUserId` int,
	`orderId` int,
	`viewedAt` timestamp,
	`acceptedAt` timestamp,
	`declinedAt` timestamp,
	`expiresAt` timestamp NOT NULL,
	`emailSentAt` timestamp,
	`reminderSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bundle_invitations_id` PRIMARY KEY(`id`),
	CONSTRAINT `bundle_invitations_token_unique` UNIQUE(`token`)
);
