export const ENV = {
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openrouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  llmDefaultProvider: process.env.LLM_DEFAULT_PROVIDER ?? "",
  llmDefaultModel: process.env.LLM_DEFAULT_MODEL ?? "",
  llmChatgptModel: process.env.LLM_CHATGPT_MODEL ?? "",
  llmClaudeModel: process.env.LLM_CLAUDE_MODEL ?? "",
  llmGeminiModel: process.env.LLM_GEMINI_MODEL ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
  publicAppUrl: process.env.PUBLIC_APP_URL ?? "",
  expoPublicAppUrl: process.env.EXPO_PUBLIC_APP_URL ?? "",
  expoPublicApiBaseUrl: process.env.EXPO_PUBLIC_API_BASE_URL ?? "",
};
